name: Build & Deploy Qlik Extension
on:
  push:
    branches:
      - master
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
      
      - name: Set Version
        run: echo "VERSION=3" >> $GITHUB_ENV
      
      - name: Obfuscate JS Files
        run: |
          npm install -g javascript-obfuscator
          javascript-obfuscator ./src --output ./dist --config ./obfuscator-config.json
      
      - name: Create ZIP Package
        run: zip -r qlik-extension-${{ env.VERSION }}.zip dist/ *.qext *.json
      
      - name: Upload to Azure Blob Storage
        run: |
          az storage blob upload \
            --account-name ${{ secrets.AZURE_STORAGE_ACCOUNT }} \
            --container-name release \
            --name qlik-extension-${{ env.VERSION }}.zip \
            --file qlik-extension-${{ env.VERSION }}.zip \
            --sas-token "${{ secrets.AZURE_SAS_TOKEN }}" \
            --overwrite
